name: Tauri Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: tauri-apps/tauri-action@v0
        with:
          projectPath: .
          releaseName: "NoDo ${{ github.ref_name }}"
          tagName: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
