name: Tauri Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Tauri CLI
        run: npm install --save-dev @tauri-apps/cli

      - name: Install GTK and dependencies
        run: |
          sudo apt update
          sudo apt install -y \
          libgtk-3-dev \
          libglib2.0-dev \
          libgobject-2.0-dev \
          libwebkit2gtk-4.1-dev \
          libssl-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev \
          pkg-config

      - uses: tauri-apps/tauri-action@v0
        with:
          projectPath: .
          releaseName: "NoDo ${{ github.ref_name }}"
          tagName: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
